print("--- MENGHITUNG LUAS DAN KELILING PERSEGI PANJANG ---")
panjang = float(input("Masukkan panjang: "))
lebar = float(input("Masukkan lebar: "))
luas = panjang * lebar
keliling = 2 * (panjang + lebar)
print("\n--- HASIL PERHITUNGAN ---")
print(f"Panjang  : {panjang}")
print(f"Lebar    : {lebar}")
print(f"Luas     : {luas}")
print(f"Keliling : {keliling}")